
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name:  my-app-v1
     labels:
       app:  my-app
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: my-app
         version: v1.0.0
     template:
       metadata:
         labels:
           app:  my-app
           version: v1.0.0
   spec:
      containers:
      - name: my-app
        image: andreadote/myapp:1
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: version
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
