apiVersion: v1
kind: Service
metadata:
  name: my-app-v1
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - name: my-app
    port: 80
    targetPort: http
# note here that we match both the app and the version
  selector:
    app: my-app 
    version: v2.0.0
