apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-28T20:19:54Z"
  generateName: demo-deployment-588cd5966d-
  labels:
    app: demo
    pod-template-hash: 588cd5966d
  name: demo-deployment-588cd5966d-6wst8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: demo-deployment-588cd5966d
    uid: 3366da99-0871-4f56-b100-160fee0f5dfc
  resourceVersion: "99045"
  uid: a60621f3-3f76-4e76-b0f4-f15551352e8a
spec:
  containers:
  - image: mylandmarktech/springapp:latest
    imagePullPolicy: Always
    name: my-spring-app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fdppj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fdppj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-28T20:19:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-28T20:19:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-28T20:19:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-28T20:19:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0ecc56b4b651fd3597a0c3f13668372ecceb9421d98e28b8c5a18030783c2ab7
    image: mylandmarktech/springapp:latest
    imageID: docker-pullable://mylandmarktech/springapp@sha256:8fcb95cd9505b7002c9e9457f6749b981e9c9de1d98ed620fb8116972f37c8b2
    lastState: {}
    name: my-spring-app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-11-28T20:19:56Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.92
  podIPs:
  - ip: 10.1.0.92
  qosClass: BestEffort
  startTime: "2023-11-28T20:19:54Z"
